### ISSUE TITLE
CachedBitmapUtility

### ISSUE THREAD

**Issue by DualBrain** [morphx666/x8086NetEmu#1]
Where do I find the assembly for the CachedBitmapUtility reference in FastCGAWinForms?

**Comment by morphx666** [comment]
I'm no longer supporting the FastCGAWinForms class.
However, here's the referenced library: https://github.com/svejdo1/CachedBitmap

**Comment by DualBrain** [comment]
Do you have a newer version that hasn't been published to here?

**Comment by morphx666** [comment]
Yes, although it still suffers from the same bugs mentioned in the [README](https://github.com/morphx666/x8086NetEmu/blob/master/README.md)

**Comment by DualBrain** [comment]
Would you mind updating the branch?  I'm very interested in helping out on this project.  I've also commented on your blog regarding your frustration with "overflow checking" with a solution.  I see that what is published here still has overflow checking enabled and I'm guessing that you wrote additional code (with additional overhead) to work around the issue.  I suspect that there is an opportunity here to improve performance by utilizing the compiler feature instead of these workarounds.

**Comment by DualBrain** [comment]
As for the "same bugs" problem; two eyes are better than one. ;-)

**Comment by DualBrain** [comment]
With the current code available; remarking out the line:

`ug.ScaleTransform(scale.Width, scale.Height)`

In RenderText() of FastCGAWinForms allowed me to get the WinForms version up and running.

It appears that ScalTransform has been removed from the CachedBitmap project.  I'm not really sure what affect this has; however, the WinForms app appears to work as desired.

Also, it's interesting to point out that the WinForms version seems to run a lot faster than the console version.  So well worth the effort in getting it up and running.

Without a doubt, this is a project that has be very excited!  Awesome work thus far.  I really look forward to participating going forward.

**Comment by morphx666** [comment]
Unfortunately, the Console class in the .NET is awfully slow.
If I'm (we're) ever able to fix the bug(s) I'll try to implement [ncurses support](https://github.com/sushihangover/CursesSharp).

As for the WinForms version: it is quite fast, but there's a lot more that can be done.
Enabling [this hack](https://github.com/morphx666/x8086NetEmu/blob/master/x8086NetEmu/Helpers/Memory.vb#L398) makes the video renderer run blazing fast.

**Comment by DualBrain** [comment]
Hah... removing the reference from the project was all I really needed to do. ;-)  With that said, now that it's confirmed we are both working with the same code... I'll definitely start digging in.  Thanks for the additional links... will explore those further as well.

**Comment by morphx666** [comment]
Couple of hints:

1. Edit and QBasic appear to suffer from the same bug. (Not sure if it matters, but FreeDos' Edit and GWBasic work just fine)
2. Defrag fails with a rather interesting error message
3. CheckIt's "Tests->System Board->[CPU Interrupt Bug](https://www.google.com/search?q=checkit+cpu+interrupt+bug" test used to work; I don't know what I changed to break this test.
