### ISSUE TITLE
CheckIt PC Diagnostics

### ISSUE THREAD

**Issue by DualBrain** [morphx666/x8086NetEmu#10]
I also found a copy of CheckIt.

Running the System Board Test:

CPU General Functions - Success
CPU Interupt Bug - locks up.  (This test passes in DosBox.)

The Video tests are acting very strange.  The log states that they passed; however, the screen just flashes strangely and immediately returns to the menus.

I found the binaries:

http://www.minuszerodegrees.net/software/software.htm

**Comment by morphx666** [comment]
The things is that I was able to correct the Interrupt Bug check... but now it's broken again.
As for the Video tests, not sure what's going on there...

**Comment by morphx666** [comment]
The latest commit not only passes the Interupt Bug test, but it passes it successfully!
As far as I know, x8086NetEmu is the only 8088 emulator that passes such test.
