### ISSUE TITLE
TupperFormula reference / errors.

### ISSUE THREAD

**Issue by DualBrain** [morphx666/x8086NetEmu#11]
Updating to the latest code, it appears that it is now using a reference to [TupperFormula](https://github.com/morphx666/TupperFormula)  I'm seeing 4 errors related to 2 lines in ButtonIcon.vb (lines 44, 48) in that project.  Parameter h not specified and Pixel is not a member of DirectBitmap.

Is there a newer version of that project?

**Comment by morphx666** [comment]
I made some changes to the DirectBitmap class so I need to update the code for the TupperFormula project.
I'll do it later tonight.

**Comment by DualBrain** [comment]
Updated... good to go.
