### ISSUE TITLE
SdlDotNet

### ISSUE THREAD

**Issue by DualBrain** [morphx666/x8086NetEmu#2]
Where do I find the SdlDotNet assembly referenced in x8086NetEmu?

**Comment by DualBrain** [comment]
I found SDL.NET (C# SDL) and downloaded sdldotnet-6.1.1.beta-sdk-setup.exe.  Is this the same/similar to what you've referenced?

https://sourceforge.net/projects/cs-sdl/files/

**Comment by morphx666** [comment]
I haven't worked on the SDL support for quite some time, so I couldn't say.

However, the functions used are pretty basic so any version should work.

**Comment by DualBrain** [comment]
Looks like this is the case, not seeing any errors related to SDL when building using what I downloaded.
