### ISSUE TITLE
<simulationMultiplier> value?

### ISSUE THREAD

**Issue by DualBrain** [morphx666/x8086NetEmu#3]
I copied some of the files from the download available at:

https://whenimbored.xfx.net/2012/10/x8086netemu-an-8086-emulator-in-vb-net/3/

> /disks
> /roms
> Perfect DOS VGA 437.ttf
> settings.dat

Into the x8086NetEmu\bin folder.

I then launch the x8086NetEmuConsole project (after finding [SdlDotNet](https://github.com/morphx666/x8086NetEmu/issues/2)).  However, it then crashes at:

`        cpu.SimulationMultiplier = Double.Parse(xml.<simulationMultiplier>.Value)`

In ParseSettings()

After adding this entry to the settings.dat file with a value of 1, things appear to work.

So the questions are:

1. What is this value for?
2. What should the value be set to as a default?
3. What values are available and what does changing it one direction or the other accomplish?

**Comment by morphx666** [comment]
The value is a hack to speed up/slow down emulation.
The WinForms version provides a context menu to set the value to 25% (0.25), 50% (0.5), 100% (1), 125 (1.25)... up to 400% (4).

However, this setting tends to break some aspects of the emulation, so leave it at "1".

**Comment by DualBrain** [comment]
Excellent!  Looks like I took a pretty good shot in the dark there. ;-)
