### ISSUE TITLE
Please update source to your current build.

### ISSUE THREAD

**Issue by DualBrain** [morphx666/x8086NetEmu#4]
As discussed [here](https://github.com/morphx666/x8086NetEmu/issues/1), can you please update to your latest local source?

Thanks in advance.

**Comment by morphx666** [comment]
I just checked the code and I'm afraid it's up to date...

**Comment by DualBrain** [comment]
Thanks for confirming that it's up to date, time to start getting a lay of the land.

**Comment by morphx666** [comment]
Thus far I've been able to use the Monitor and the Console debugging tools to fix most of the issues I've encountered. They're not perfect and I'm aware that are quite buggy.

So, please, let me know of any changes and/or additions that could be made to those tools to facilitate the troubleshooting of the emulator.
