### ISSUE TITLE
QBasic problem / possible diagnostic...

### ISSUE THREAD

**Issue by DualBrain** [morphx666/x8086NetEmu#6]
Playing around with different versions of what eventually became qbasic.exe (BASIC PDS 7.1, QB 4.5), very similar issues happen as qbasic.exe... so at least it's consistent.  The thought crossed my mind as to whether or not there might be any command line compatibility 

`C:\>qbasic /?`

Results in a bunch of a's and e's... and not entirely in the same positions as where the proper text should be.  This might be of interest since this, in theory, should be less code as the console help is usually one of the first points that most apps would hit... at least it's what I'm thinking in my head.

I did try all of the switches, not really any noticeable affect.

I also wondered if it would execute if I loaded it with a file...

I created the following (test.bas):

`PRINT "HELLO WORLD!"`

and then...

`qbasic test.bas`

Interestingly enough, it seems to have the same text problem... odd.  So whatever the issue is, it appears to be carrying through to the interpreter as well.  Strange.

I'm not familiar enough with the code base and, well emulation, yet to know if this might help.

**Comment by morphx666** [comment]
This has been fixed since commit 375e50b42557459545b2edcb6e8a2fb39fc8903f
