### ISSUE TITLE
PC Diagnostics '95

### ISSUE THREAD

**Issue by DualBrain** [morphx666/x8086NetEmu#8]
Looking for different diagnostics (MSD.EXE fails), I found...

ftp://ftp.sac.sk/sac/utildiag/diags.zip

on 

http://www.bttr-software.de/freesoft/system.htm

It works in many cases; and in others, it locks up.  Not sure of it's usefulness; but figured I'd add it to the possibilities list.

One thing that does jump out at me is the System BIOS Type:  XT, Unknown BIOS Type
And the CPU Type: Intel, 80188.

Does that seem correct?

**Comment by morphx666** [comment]
Yes, those specs are correct.
